package ru.aeronautics.client.ponder;

import net.minecraft.resources.ResourceLocation;
import net.neoforged.neoforge.registries.DeferredHolder;

import net.createmod.ponder.api.registration.PonderTagRegistrationHelper;

import ru.tfc_aeronautics.Aeronautics;
import ru.tfc_aeronautics.heater.HeaterRegistration;
import ru.tfc_aeronautics.stamping_press.StampingPressRegistration;

/**
 * Tag (UI category) registration for the Ponder Index.
 *
 * Each tag groups a set of blocks under a named category visible in Ponder's UI.
 * Two-step registration: declare the tag with title/description/icon, then fill it.
 *
 * Lang keys (auto-generated by datagen via providePonderLang):
 *   tfc_aeronautics.ponder.tag.<tag_id>          — category title
 *   tfc_aeronautics.ponder.tag.<tag_id>.desc     — category description (if registered as such)
 */
public final class AeronauticsPonderTags {

    public static final ResourceLocation AERONAUTICS_KINETICS =
        ResourceLocation.fromNamespaceAndPath(Aeronautics.MOD_ID, "aeronautics_kinetics");

    private AeronauticsPonderTags() {}

    public static void register(PonderTagRegistrationHelper<ResourceLocation> helper) {
        PonderTagRegistrationHelper<DeferredHolder<?, ?>> blockHelper =
            helper.withKeyFunction(h -> h.getKey().location());

        helper.registerTag(AERONAUTICS_KINETICS)
            .addToIndex()
            .item(HeaterRegistration.HEATER.get(), true, false)
            .title("Aeronautics Kinetics")
            .description("Components built around Create's kinetic system")
            .register();

        blockHelper.addToTag(AERONAUTICS_KINETICS)
            .add(HeaterRegistration.HEATER)
            .add(StampingPressRegistration.STAMPING_PRESS);
    }
}