package ru.aeronautics.client.ponder;

import net.minecraft.resources.ResourceLocation;
import net.neoforged.neoforge.registries.DeferredHolder;

import net.createmod.ponder.api.registration.PonderTagRegistrationHelper;

import ru.tfc_aeronautics.TFCAeronautics;
import ru.tfc_aeronautics.condenser_coil.CondenserCoilRegistration;
import ru.tfc_aeronautics.heater.HeaterRegistration;
import ru.tfc_aeronautics.stamping_press.StampingPressRegistration;

/**
 * Tag (UI category) registration for the Ponder Index.
 *
 * Each tag groups a set of blocks under a named category visible in Ponder's UI.
 * Two-step registration: declare the tag with title/description/icon, then fill it.
 *
 * Lang keys (auto-generated by datagen via providePonderLang):
 *   tfc_aeronautics.ponder.tag.<tag_id>          — category title
 *   tfc_aeronautics.ponder.tag.<tag_id>.desc     — category description (if registered as such)
 */
public final class PonderTags {

    public static final ResourceLocation KINETIC_APPLIANCES = ResourceLocation.fromNamespaceAndPath("create", "kinetic_appliances");
    public static final ResourceLocation FLUIDS = ResourceLocation.fromNamespaceAndPath("create", "fluids");

    private PonderTags() {}

    public static void register(PonderTagRegistrationHelper<ResourceLocation> helper) {
        PonderTagRegistrationHelper<DeferredHolder<?, ?>> blockHelper =
            helper.withKeyFunction(h -> h.getKey().location());

        blockHelper.addToTag(FLUIDS)
            .add(CondenserCoilRegistration.CONDENSER_COIL);

        blockHelper.addToTag(KINETIC_APPLIANCES)
            .add(StampingPressRegistration.STAMPING_PRESS);
    }
}
